### ISSUE TITLE
Doesn't work with tools that send SIGUSR1

### ISSUE THREAD

**Issue by dandv** [oliversalzburg/debugger-attached#1]
See https://github.com/IonicaBizau/debug-mode/issues/15

[Race on](https://github.com/IonicaBizau/debug-mode/issues/2)? :smile:

**Comment by oliversalzburg** [comment]
Oh nice, more duplication and he made the necessary change already in his copy.

Honestly, if you want this in your code, don't pull in a third-party dependency for it. Implement that yourself.
